# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MfcBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=40)),
                ('uuid', models.CharField(max_length=40)),
                ('bet', models.FloatField(blank=True, null=True)),
                ('win', models.IntegerField(blank=True, null=True)),
                ('fighter_uuid', models.CharField(max_length=40)),
                ('fighter_name', models.CharField(max_length=40)),
                ('odds', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mfc_bet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MfcFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('kit', models.CharField(max_length=40)),
                ('stage', models.CharField(max_length=40)),
                ('uuid1', models.CharField(max_length=40)),
                ('uuid2', models.CharField(max_length=40)),
                ('player1', models.CharField(max_length=40)),
                ('player2', models.CharField(max_length=40)),
                ('odds1', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('odds2', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('bet1', models.IntegerField(blank=True, null=True)),
                ('bet2', models.IntegerField(blank=True, null=True)),
                ('totalbet', models.FloatField(blank=True, null=True)),
                ('prize', models.FloatField(blank=True, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=40, null=True)),
                ('loser', models.CharField(blank=True, max_length=40, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mfc_fight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MfcproBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=40)),
                ('uuid', models.CharField(max_length=40)),
                ('bet', models.FloatField(blank=True, null=True)),
                ('win', models.IntegerField(blank=True, null=True)),
                ('fighter_uuid', models.CharField(max_length=40)),
                ('fighter_name', models.CharField(max_length=40)),
                ('odds', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mfcpro_bet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MfcproFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('kit', models.CharField(max_length=40)),
                ('stage', models.CharField(max_length=40)),
                ('uuid1', models.CharField(max_length=40)),
                ('uuid2', models.CharField(max_length=40)),
                ('player1', models.CharField(max_length=40)),
                ('player2', models.CharField(max_length=40)),
                ('odds1', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('odds2', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('bet1', models.IntegerField(blank=True, null=True)),
                ('bet2', models.IntegerField(blank=True, null=True)),
                ('totalbet', models.FloatField(blank=True, null=True)),
                ('prize', models.FloatField(blank=True, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=40, null=True)),
                ('loser', models.CharField(blank=True, max_length=40, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mfcpro_fight',
                'managed': False,
            },
        ),
    ]
