# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdaChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.CharField(max_length=50)),
                ('chat', models.CharField(max_length=1024)),
                ('world', models.CharField(max_length=128)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('time', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pda_chat_log',
                'managed': False,
            },
        ),
    ]
